# Challenge : Analyse de la data

- Lire all-ages.csv dans un DataFrame et l'assigner à la variable all_ages.

- Lire recent-grads.csv dans un DataFrame et l'assigner à la variable recent_grads.

- Afficher les 5 premières lignes de all_ages et recent_grads.

In [1]:
import pandas as pd

all_ages = pd.read_csv("all-ages.csv")
all_ages

,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148.0,90245.0,74078.0,2423.0,0.026147,50000.0,34000.0,80000.0
1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326.0,76865.0,64240.0,2266.0,0.028636,54000.0,36000.0,80000.0
2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955.0,26321.0,22810.0,821.0,0.030248,63000.0,40000.0,98000.0
3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549.0,81177.0,64937.0,3619.0,0.042679,46000.0,30000.0,72000.0
4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280.0,17281.0,12722.0,894.0,0.049188,62000.0,38500.0,90000.0
...,...,...,...,...,...,...,...,...,...,...,...
168,6211,HOSPITALITY MANAGEMENT,Business,200854.0,163393.0,122499.0,8862.0,0.051447,49000.0,33000.0,70000.0
169,6212,MANAGEMENT INFORMATION SYSTEMS AND STATISTICS,Business,156673.0,134478.0,118249.0,6186.0,0.043977,72000.0,50000.0,100000.0
170,6299,MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION,Business,102753.0,77471.0,61603.0,4308.0,0.052679,53000.0,36000.0,83000.0
171,6402,HISTORY,Humanities & Liberal Arts,712509.0,478416.0,354163.0,33725.0,0.065851,50000.0,35000.0,80000.0
172,6403,UNITED STATES HISTORY,Humanities & Liberal Arts,17746.0,11887.0,8204.0,943.0,0.073500,50000.0,39000.0,81000.0

In [2]:
import pandas as pd

recent_grads = pd.read_csv("recent-grads.csv")
recent_grads

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419.0,PETROLEUM ENGINEERING,Engineering,2339.0,36.0,2057.0,282.0,0.120564,1976.0,...,270.0,1207.0,37.0,0.018381,110000.0,95000.0,125000.0,1534.0,364.0,193.0
1,2,2416.0,MINING AND MINERAL ENGINEERING,Engineering,756.0,7.0,679.0,77.0,0.101852,640.0,...,170.0,388.0,85.0,0.117241,75000.0,55000.0,90000.0,350.0,257.0,50.0
2,3,2415.0,METALLURGICAL ENGINEERING,Engineering,856.0,3.0,725.0,131.0,0.153037,648.0,...,133.0,340.0,16.0,0.024096,73000.0,50000.0,105000.0,456.0,176.0,0.0
3,4,2417.0,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258.0,16.0,1123.0,135.0,0.107313,758.0,...,150.0,692.0,40.0,0.050125,70000.0,43000.0,80000.0,529.0,102.0,0.0
4,5,2405.0,CHEMICAL ENGINEERING,Engineering,32260.0,289.0,21239.0,11021.0,0.341631,25694.0,...,5180.0,16697.0,1672.0,0.061098,65000.0,50000.0,75000.0,18314.0,4440.0,972.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,169,3609.0,ZOOLOGY,Biology & Life Science,8409.0,47.0,3050.0,5359.0,0.637293,6259.0,...,2190.0,3602.0,304.0,0.046320,26000.0,20000.0,39000.0,2771.0,2947.0,743.0
169,170,5201.0,EDUCATIONAL PSYCHOLOGY,Psychology & Social Work,2854.0,7.0,522.0,2332.0,0.817099,2125.0,...,572.0,1211.0,148.0,0.065112,25000.0,24000.0,34000.0,1488.0,615.0,82.0
170,171,5202.0,CLINICAL PSYCHOLOGY,Psychology & Social Work,2838.0,13.0,568.0,2270.0,0.799859,2101.0,...,648.0,1293.0,368.0,0.149048,25000.0,25000.0,40000.0,986.0,870.0,622.0
171,172,5203.0,COUNSELING PSYCHOLOGY,Psychology & Social Work,4626.0,21.0,931.0,3695.0,0.798746,3777.0,...,965.0,2738.0,214.0,0.053621,23400.0,19200.0,26000.0,2403.0,1245.0,308.0
172,173,3501.0,LIBRARY SCIENCE,Education,1098.0,2.0,134.0,964.0,0.877960,742.0,...,237.0,410.0,87.0,0.104946,22000.0,20000.0,22000.0,288.0,338.0,192.0

In [5]:
# Afficher les 5 premières lignes du premier dataframe
all_ages.head()

,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148.0,90245.0,74078.0,2423.0,0.026147,50000.0,34000.0,80000.0
1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326.0,76865.0,64240.0,2266.0,0.028636,54000.0,36000.0,80000.0
2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955.0,26321.0,22810.0,821.0,0.030248,63000.0,40000.0,98000.0
3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549.0,81177.0,64937.0,3619.0,0.042679,46000.0,30000.0,72000.0
4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280.0,17281.0,12722.0,894.0,0.049188,62000.0,38500.0,90000.0

In [6]:
# Afficher les 5 premières lignes du deuxième dataframe
recent_grads.head()

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419.0,PETROLEUM ENGINEERING,Engineering,2339.0,36.0,2057.0,282.0,0.120564,1976.0,...,270.0,1207.0,37.0,0.018381,110000.0,95000.0,125000.0,1534.0,364.0,193.0
1,2,2416.0,MINING AND MINERAL ENGINEERING,Engineering,756.0,7.0,679.0,77.0,0.101852,640.0,...,170.0,388.0,85.0,0.117241,75000.0,55000.0,90000.0,350.0,257.0,50.0
2,3,2415.0,METALLURGICAL ENGINEERING,Engineering,856.0,3.0,725.0,131.0,0.153037,648.0,...,133.0,340.0,16.0,0.024096,73000.0,50000.0,105000.0,456.0,176.0,0.0
3,4,2417.0,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258.0,16.0,1123.0,135.0,0.107313,758.0,...,150.0,692.0,40.0,0.050125,70000.0,43000.0,80000.0,529.0,102.0,0.0
4,5,2405.0,CHEMICAL ENGINEERING,Engineering,32260.0,289.0,21239.0,11021.0,0.341631,25694.0,...,5180.0,16697.0,1672.0,0.061098,65000.0,50000.0,75000.0,18314.0,4440.0,972.0

## Nombre d'étudiants par catégorie de major

- Retourner les valeurs uniques de Major_category
    - Utiliser la méthode Series.unique() pour retourner les valeurs uniques d'une Series.

In [8]:
all_ages["Major_category"].unique()

array(['Agriculture & Natural Resources', 'Biology & Life Science',
       'Engineering', 'Humanities & Liberal Arts',
       'Communications & Journalism', 'Computers & Mathematics',
       'Industrial Arts & Consumer Services', 'Education',
       'Law & Public Policy', 'Interdisciplinary', 'Health',
       'Social Science', 'Physical Sciences', nan,
       'Psychology & Social Work', 'Arts', 'Business'], dtype=object)

- Pour chaque valeur unique (utilisation d'une boucle for?) :

    - Retourner toutes les lignes où Major_category vaut cette valeur unique.

    - Calculer le nombre total d'étudiants représentant cette catégorie de major (colonne Total à sommer).

    - Vous garderez en mémoire ce résultat sous la forme d'un dictionnaire contenant une Major_category en clé et le nombre d'étudiants en valeur.

In [10]:
# Nombre total d'étudiants récemment diplômé
recent_grads["Total"].sum()

6771464.0

- Créer une fonction dans laquelle vous utiliserez la colonne Total pour calculer le nombre d'étudiants pour chaque catégorie de Major (Major_category) dans chaque dataset.

    - Stocker le résultat dans 2 dictionnaires distincts

    - La clé pour chaque dictionnaire sera Major_category et la valeur le total d'étudiants

    - Pour le dataset all_ages, stocker le résultat dans un dictionnaire qu'on nommera aa_car_counts

    - Pour le dataset recent_grads, stocker le résultat dans un dictionnaire qu'on nommera rg_cat_counts

- Autre méthode : Utiliser un pivot de table.

- Afficher les 2 dictionnaires.

In [13]:
# On va utiliser comme paramétre un dataframe
def calculate_major_cat_totals(df):
    cats = df["Major_category"].unique()
    counts_dictionary = dict()

    for c in cats:
    # On va récupérer un dataframe qui correspond à chaque catégorie de major
        major_df = df[df["Major_category"] == c]
        total = major_df["Total"].sum()
        counts_dictionary[c] = total
    return counts_dictionary

In [14]:
aa_cat_counts = dict()
aa_cat_counts = calculate_major_cat_totals(all_ages)
print(aa_cat_counts)

{'Agriculture & Natural Resources': 632437.0, 'Biology & Life Science': 1338186.0, 'Engineering': 3576013.0, 'Humanities & Liberal Arts': 3738335.0, 'Communications & Journalism': 1803822.0, 'Computers & Mathematics': 1781378.0, 'Industrial Arts & Consumer Services': 1018072.0, 'Education': 4700118.0, 'Law & Public Policy': 902926.0, 'Interdisciplinary': 45199.0, 'Health': 2950859.0, 'Social Science': 2654125.0, 'Physical Sciences': 1013152.0, nan: 0.0, 'Psychology & Social Work': 1987278.0, 'Arts': 1805865.0, 'Business': 9858741.0}

In [15]:
rg_cat_counts = dict()
rg_cat_counts = calculate_major_cat_totals(recent_grads)
print(rg_cat_counts)

{'Engineering': 537583.0, 'Business': 1302376.0, 'Physical Sciences': 183363.0, 'Law & Public Policy': 179107.0, 'Computers & Mathematics': 299008.0, 'Agriculture & Natural Resources': 79981.0, 'Industrial Arts & Consumer Services': 227357.0, 'Arts': 357130.0, 'Health': 463230.0, 'Social Science': 529966.0, nan: 0.0, 'Biology & Life Science': 453862.0, 'Education': 559129.0, 'Humanities & Liberal Arts': 713468.0, 'Psychology & Social Work': 481007.0, 'Communications & Journalism': 392601.0, 'Interdisciplinary': 12296.0}

### Autre Méthode Pivot_table

In [18]:
import numpy as np
aa_cat_counts = dict(all_ages.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))
print(aa_cat_counts)

{'Total': Major_category
Agriculture & Natural Resources         632437.0
Arts                                   1805865.0
Biology & Life Science                 1338186.0
Business                               9858741.0
Communications & Journalism            1803822.0
Computers & Mathematics                1781378.0
Education                              4700118.0
Engineering                            3576013.0
Health                                 2950859.0
Humanities & Liberal Arts              3738335.0
Industrial Arts & Consumer Services    1018072.0
Interdisciplinary                        45199.0
Law & Public Policy                     902926.0
Physical Sciences                      1013152.0
Psychology & Social Work               1987278.0
Social Science                         2654125.0
Name: Total, dtype: float64}

/var/folders/rg/f7ng39g91739cyddknxt75d40000gn/T/ipykernel_57947/1022104401.py:2: FutureWarning: The provided callable <function sum at 0x104a99ee0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  aa_cat_counts = dict(all_ages.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))

In [19]:
import numpy as np
rg_cat_counts = dict(recent_grads.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))
print(rg_cat_counts)

{'Total': Major_category
Agriculture & Natural Resources          79981.0
Arts                                    357130.0
Biology & Life Science                  453862.0
Business                               1302376.0
Communications & Journalism             392601.0
Computers & Mathematics                 299008.0
Education                               559129.0
Engineering                             537583.0
Health                                  463230.0
Humanities & Liberal Arts               713468.0
Industrial Arts & Consumer Services     227357.0
Interdisciplinary                        12296.0
Law & Public Policy                     179107.0
Physical Sciences                       183363.0
Psychology & Social Work                481007.0
Social Science                          529966.0
Name: Total, dtype: float64}

/var/folders/rg/f7ng39g91739cyddknxt75d40000gn/T/ipykernel_57947/1035153426.py:2: FutureWarning: The provided callable <function sum at 0x104a99ee0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  rg_cat_counts = dict(recent_grads.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))

## Taux de jobs à faible salaire

- Utiliser les colonnes "Low_wage_jobs" et "Total" pour calculer la proportion de jeunes diplômés qui ont du trouver des jobs à faible salaire (recent_grads).

    - Souvenez-vous que vous pouvez utiliser la méthode Series.sum() pour retourner la somme des valeurs d'une colonne

- Stocker le résultat dans la variable low_wage_proportion et afficher le.

In [20]:
low_wage_jobs_sum = recent_grads["Low_wage_jobs"].sum()
recent_grads_sum = recent_grads["Total"].sum()

low_wage_proportion = low_wage_jobs_sum/recent_grads_sum
print(low_wage_proportion)

0.09856140415130317

## Comparer des datasets

- Utiliser une boucle for pour parcourir toutes les majors.

    - Pour chaque Major et chaque DataFrame, filtrer seulement les lignes du DataFrame correspondant à cette major

    - Comparer les valeurs pour la colonne "Unemployment_rate" pour voir lequel des 2 DataFrames possèdent la valeur la plus basse

    - Incrémenter (cad ajouter 1) à la variable rg_lower_count si la valeur pour Unemployment_rate est plus petite dans le dataframe recent_grads que dans le dataframe all_ages

- Afficher le résultat rg_lower_count.

In [22]:
# Liste des majors communes à nos 2 DataFrames
majors = recent_grads["Major"].unique()

In [27]:
rg_lower_count = 0

for m in majors: 
    recent_grads_row = recent_grads[recent_grads["Major"] == m]
    all_ages_row = all_ages[all_ages["Major"] == m]

    rg_unemp_rate = recent_grads_row["Unemployment_rate"].values 
    aa_unemp_rate = all_ages_row["Unemployment_rate"].values

    if rg_unemp_rate < aa_unemp_rate:
        rg_lower_count += 1

print(rg_lower_count)

42

/var/folders/rg/f7ng39g91739cyddknxt75d40000gn/T/ipykernel_57947/3778001442.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if rg_unemp_rate < aa_unemp_rate: